apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool-logs
  namespace: shared-app
spec:
  selector:
    matchLabels:
      app: multitool-logs
  template:
    metadata:
      labels:
        app: multitool-logs
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Чтение системного лога ноды...";
              tail -f /host/var/log/syslog
          volumeMounts:
            - name: host-logs
              mountPath: /host/var/log
              readOnly: true
      volumes:
        - name: host-logs
          hostPath:
            path: /var/log
            type: Directory
